function heatmaps8(recordingobject)
    % Given an input Recording8 object, plots all 6 simultaneously-measured
    % raw signals for the tests in Figures 3 & 4.

    subplot(2,3,1);
    heatmap(normalize(recordingobject.rms10k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    title("10kHz RMS");
    subplot(2,3,2);
    heatmap(normalize(recordingobject.rms50k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    title("50kHz RMS");
    subplot(2,3,3);
    heatmap(normalize(recordingobject.rms100k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    title("100kHz RMS");
    subplot(2,3,4);
    heatmap(normalize(recordingobject.phase10k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    title("10kHz Phase");
    subplot(2,3,5);
    heatmap(normalize(recordingobject.phase50k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    title("50kHz Phase");
    subplot(2,3,6);
    heatmap(normalize(recordingobject.phase100k, "range", [0 1]).',...
        "colormap", gray, 'XDisplayLabels',NaN*ones(size(recordingobject.rms10k, 1),1),...
        'YDisplayLabels',NaN*ones(size(recordingobject.rms10k, 2),1)); grid off; colorbar off
    set(gcf, 'Position', [193 334 1124 418], 'Color', 'w');
    title("100kHz Phase");
end